/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TmsCancellationResult } from '../../models/tms-cancellation-result';

export interface CancelSigningRequestForUser$Params {
  deviceId: number;
}

export function cancelSigningRequestForUser(http: HttpClient, rootUrl: string, params: CancelSigningRequestForUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TmsCancellationResult>>> {
  const rb = new RequestBuilder(rootUrl, cancelSigningRequestForUser.PATH, 'get');
  if (params) {
    rb.path('deviceId', params.deviceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TmsCancellationResult>>;
    })
  );
}

cancelSigningRequestForUser.PATH = '/resources/openapi/secureOnlineBankingApi/TwoFactorService/cancelSigningRequestForUser/{deviceId}';
