/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PortfolioSummaryWrapper } from '../../models/portfolio-summary-wrapper';

export interface CheckAndGetPortfolioOverview$Params {
  portfolioAccountUuid: string;
  hash: string;
}

export function checkAndGetPortfolioOverview(http: HttpClient, rootUrl: string, params: CheckAndGetPortfolioOverview$Params, context?: HttpContext): Observable<StrictHttpResponse<PortfolioSummaryWrapper>> {
  const rb = new RequestBuilder(rootUrl, checkAndGetPortfolioOverview.PATH, 'get');
  if (params) {
    rb.path('portfolioAccountUuid', params.portfolioAccountUuid, {});
    rb.path('hash', params.hash, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PortfolioSummaryWrapper>;
    })
  );
}

checkAndGetPortfolioOverview.PATH = '/resources/openapi/secureOnlineBankingApi/SecurityBookingLineService/checkAndGetPortfolioOverview/{portfolioAccountUuid}/{hash}';
