/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperPaymentOrder } from '../../models/dialog-wrapper-payment-order';
import { Xs2AConfirmationRequest } from '../../models/xs-2-a-confirmation-request';

export interface CreateXs2APaymentConfirmationRequest$Params {
      body: Xs2AConfirmationRequest
}

export function createXs2APaymentConfirmationRequest(http: HttpClient, rootUrl: string, params: CreateXs2APaymentConfirmationRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperPaymentOrder>> {
  const rb = new RequestBuilder(rootUrl, createXs2APaymentConfirmationRequest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperPaymentOrder>;
    })
  );
}

createXs2APaymentConfirmationRequest.PATH = '/resources/openapi/secureOpenBankingApi/OnlineBankingXs2aPaymentService/createXs2aPaymentConfirmationRequest';
