/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountClassStrings } from '../../models/account-class-strings';
import { DialogWrapperForNonAuditedEntitiesBoolean } from '../../models/dialog-wrapper-for-non-audited-entities-boolean';

export interface CreateOrderRequest1$Params {
      body?: Array<AccountClassStrings>
}

export function createOrderRequest1(http: HttpClient, rootUrl: string, params?: CreateOrderRequest1$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperForNonAuditedEntitiesBoolean>> {
  const rb = new RequestBuilder(rootUrl, createOrderRequest1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperForNonAuditedEntitiesBoolean>;
    })
  );
}

createOrderRequest1.PATH = '/resources/openapi/secureOnlineBankingApi/SigningService/createOrderRequestWithDevice';
