/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperXs2AConsent } from '../../models/dialog-wrapper-xs-2-a-consent';
import { Xs2AConfirmationRequest } from '../../models/xs-2-a-confirmation-request';

export interface CreateXs2AConsentConfirmationRequest1$Params {
      body: Xs2AConfirmationRequest
}

export function createXs2AConsentConfirmationRequest1(http: HttpClient, rootUrl: string, params: CreateXs2AConsentConfirmationRequest1$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperXs2AConsent>> {
  const rb = new RequestBuilder(rootUrl, createXs2AConsentConfirmationRequest1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperXs2AConsent>;
    })
  );
}

createXs2AConsentConfirmationRequest1.PATH = '/resources/openapi/secureOpenBankingApi/OnlineBankingXs2aConsentService/createXs2aConsentConfirmationRequest';
