/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TmsActivationCodeInfo } from '../../models/tms-activation-code-info';

export interface CreateNewActivationCode$Params {
}

export function createNewActivationCode(http: HttpClient, rootUrl: string, params?: CreateNewActivationCode$Params, context?: HttpContext): Observable<StrictHttpResponse<TmsActivationCodeInfo>> {
  const rb = new RequestBuilder(rootUrl, createNewActivationCode.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TmsActivationCodeInfo>;
    })
  );
}

createNewActivationCode.PATH = '/resources/openapi/secureOnlineBankingApi/TwoFactorService/createNewActivationCode';
