/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperCollectionForNonAuditedEntitiesBoolean } from '../../models/dialog-wrapper-collection-for-non-audited-entities-boolean';

export interface DeletePaymentOrder1$Params {
      body?: Array<string>
}

export function deletePaymentOrder1(http: HttpClient, rootUrl: string, params?: DeletePaymentOrder1$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperCollectionForNonAuditedEntitiesBoolean>> {
  const rb = new RequestBuilder(rootUrl, deletePaymentOrder1.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperCollectionForNonAuditedEntitiesBoolean>;
    })
  );
}

deletePaymentOrder1.PATH = '/resources/openapi/secureOnlineBankingApi/PaymentOrderService/deletePaymentOrders';
