/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperCollectionOnlineBankingSecurityOrder } from '../../models/dialog-wrapper-collection-online-banking-security-order';

export interface DeleteSecurityOrders$Params {
      body?: Array<string>
}

export function deleteSecurityOrders(http: HttpClient, rootUrl: string, params?: DeleteSecurityOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperCollectionOnlineBankingSecurityOrder>> {
  const rb = new RequestBuilder(rootUrl, deleteSecurityOrders.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperCollectionOnlineBankingSecurityOrder>;
    })
  );
}

deleteSecurityOrders.PATH = '/resources/openapi/secureOnlineBankingApi/SecurityOrderService/deleteSecurityOrders';
