/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteTmsDevice$Params {
  deviceId: number;
  forceRemoval: boolean;
}

export function deleteTmsDevice(http: HttpClient, rootUrl: string, params: DeleteTmsDevice$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, deleteTmsDevice.PATH, 'get');
  if (params) {
    rb.path('deviceId', params.deviceId, {});
    rb.path('forceRemoval', params.forceRemoval, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

deleteTmsDevice.PATH = '/resources/openapi/secureOnlineBankingApi/TwoFactorService/deleteTmsDevice/{deviceId}/{forceRemoval}';
