/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperXs2AConsent } from '../../models/dialog-wrapper-xs-2-a-consent';

export interface DeleteXs2AConsent$Params {
  toBeDeletedConsentId: string;
}

export function deleteXs2AConsent(http: HttpClient, rootUrl: string, params: DeleteXs2AConsent$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperXs2AConsent>> {
  const rb = new RequestBuilder(rootUrl, deleteXs2AConsent.PATH, 'get');
  if (params) {
    rb.path('toBeDeletedConsentId', params.toBeDeletedConsentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperXs2AConsent>;
    })
  );
}

deleteXs2AConsent.PATH = '/resources/openapi/secureOnlineBankingApi/Xs2aConsentService/deleteXs2aConsent/{toBeDeletedConsentId}';
