/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperForNonAuditedEntitiesBoolean } from '../../models/dialog-wrapper-for-non-audited-entities-boolean';

export interface DeletePaymentOrder$Params {
  toBeDeletedUUID: string;
}

export function deletePaymentOrder(http: HttpClient, rootUrl: string, params: DeletePaymentOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperForNonAuditedEntitiesBoolean>> {
  const rb = new RequestBuilder(rootUrl, deletePaymentOrder.PATH, 'get');
  if (params) {
    rb.path('toBeDeletedUUID', params.toBeDeletedUUID, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperForNonAuditedEntitiesBoolean>;
    })
  );
}

deletePaymentOrder.PATH = '/resources/openapi/secureOnlineBankingApi/PaymentOrderService/deletePaymentOrder/{toBeDeletedUUID}';
