/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageAttachment } from '../../models/message-attachment';

export interface DownloadInboundMessageAttachment$Params {
  attachmentAuditUuid: string;
}

export function downloadInboundMessageAttachment(http: HttpClient, rootUrl: string, params: DownloadInboundMessageAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageAttachment>> {
  const rb = new RequestBuilder(rootUrl, downloadInboundMessageAttachment.PATH, 'get');
  if (params) {
    rb.path('attachmentAuditUuid', params.attachmentAuditUuid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessageAttachment>;
    })
  );
}

downloadInboundMessageAttachment.PATH = '/resources/openapi/secureOnlineBankingApi/OnlineBankingMessageService/downloadInboundMessageAttachment/{attachmentAuditUuid}';
