/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageAttachment } from '../../models/message-attachment';

export interface DownloadOutboundMessageAttachment$Params {
  attachmentAuditUuid: string;
}

export function downloadOutboundMessageAttachment(http: HttpClient, rootUrl: string, params: DownloadOutboundMessageAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageAttachment>> {
  const rb = new RequestBuilder(rootUrl, downloadOutboundMessageAttachment.PATH, 'get');
  if (params) {
    rb.path('attachmentAuditUuid', params.attachmentAuditUuid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessageAttachment>;
    })
  );
}

downloadOutboundMessageAttachment.PATH = '/resources/openapi/secureOnlineBankingApi/OnlineBankingMessageService/downloadOutboundMessageAttachment/{attachmentAuditUuid}';
