/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExportFile } from '../../models/export-file';
import { ExportRequest } from '../../models/export-request';

export interface ExportFile$Params {
      body: ExportRequest
}

export function exportFile(http: HttpClient, rootUrl: string, params: ExportFile$Params, context?: HttpContext): Observable<StrictHttpResponse<ExportFile>> {
  const rb = new RequestBuilder(rootUrl, exportFile.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExportFile>;
    })
  );
}

exportFile.PATH = '/resources/openapi/secureOnlineBankingApi/onlineBankingUniversalDataExporterService/exportFile';
