/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GenerateAddDeviceConfirmationRequest$Params {
  deviceId: number;
}

export function generateAddDeviceConfirmationRequest(http: HttpClient, rootUrl: string, params: GenerateAddDeviceConfirmationRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, generateAddDeviceConfirmationRequest.PATH, 'get');
  if (params) {
    rb.path('deviceId', params.deviceId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

generateAddDeviceConfirmationRequest.PATH = '/resources/openapi/secureOnlineBankingApi/TwoFactorService/generateAddDeviceConfirmationRequest/{deviceId}';
