/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GozoCurrency } from '../../models/gozo-currency';

export interface GetPaymentCurrencies$Params {
}

export function getPaymentCurrencies(http: HttpClient, rootUrl: string, params?: GetPaymentCurrencies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GozoCurrency>>> {
  const rb = new RequestBuilder(rootUrl, getPaymentCurrencies.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GozoCurrency>>;
    })
  );
}

getPaymentCurrencies.PATH = '/resources/openapi/secureOnlineBankingApi/PaymentOrderService/getPaymentCurrencies';
