/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FaqEntry } from '../../models/faq-entry';

export interface GetFaQs$Params {
}

export function getFaQs(http: HttpClient, rootUrl: string, params?: GetFaQs$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FaqEntry>>> {
  const rb = new RequestBuilder(rootUrl, getFaQs.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FaqEntry>>;
    })
  );
}

getFaQs.PATH = '/resources/openapi/secureOnlineBankingApi/FaqService/getFAQs';
