/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TmsUserDevice } from '../../models/tms-user-device';

export interface GetTmsDevicesForUser$Params {
  ignoreAddedDevices: boolean;
}

export function getTmsDevicesForUser(http: HttpClient, rootUrl: string, params: GetTmsDevicesForUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TmsUserDevice>>> {
  const rb = new RequestBuilder(rootUrl, getTmsDevicesForUser.PATH, 'get');
  if (params) {
    rb.path('ignoreAddedDevices', params.ignoreAddedDevices, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TmsUserDevice>>;
    })
  );
}

getTmsDevicesForUser.PATH = '/resources/openapi/secureOnlineBankingApi/TwoFactorService/getTmsDevicesForUser/{ignoreAddedDevices}';
