/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentStatusEvent } from '../../models/payment-status-event';

export interface GetPaymentStatusUpdateEvents$Params {
  
    /**
     * list of payment order uuids
     */
    body: Array<string>
}

export function getPaymentStatusUpdateEvents(http: HttpClient, rootUrl: string, params: GetPaymentStatusUpdateEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PaymentStatusEvent>>> {
  const rb = new RequestBuilder(rootUrl, getPaymentStatusUpdateEvents.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PaymentStatusEvent>>;
    })
  );
}

getPaymentStatusUpdateEvents.PATH = '/resources/openapi/secureOnlineBankingApi/PaymentOrderService/statusUpdateEvents';
