/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserLoginEvent } from '../../models/user-login-event';

export interface GetLastUserLoginEvent$Params {
}

export function getLastUserLoginEvent(http: HttpClient, rootUrl: string, params?: GetLastUserLoginEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<UserLoginEvent>> {
  const rb = new RequestBuilder(rootUrl, getLastUserLoginEvent.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserLoginEvent>;
    })
  );
}

getLastUserLoginEvent.PATH = '/resources/openapi/secureOnlineBankingApi/UserAuthenticationService/getLastUserLoginEvent';
