/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperForNonAuditedEntitiesString } from '../../models/dialog-wrapper-for-non-audited-entities-string';

export interface GetXs2AXrequestIdByPaymentId$Params {
  paymentId: string;
}

export function getXs2AXrequestIdByPaymentId(http: HttpClient, rootUrl: string, params: GetXs2AXrequestIdByPaymentId$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperForNonAuditedEntitiesString>> {
  const rb = new RequestBuilder(rootUrl, getXs2AXrequestIdByPaymentId.PATH, 'get');
  if (params) {
    rb.path('paymentId', params.paymentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperForNonAuditedEntitiesString>;
    })
  );
}

getXs2AXrequestIdByPaymentId.PATH = '/resources/openapi/secureOpenBankingApi/OnlineBankingXs2aPaymentService/getXs2aXrequestIdByPaymentId/{paymentId}';
