/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperForNonAuditedEntitiesTppCertificateInformation } from '../../models/dialog-wrapper-for-non-audited-entities-tpp-certificate-information';

export interface GetTppCertificateInformationOpenBanking$Params {
  certificateTokenHash: string;
}

export function getTppCertificateInformationOpenBanking(http: HttpClient, rootUrl: string, params: GetTppCertificateInformationOpenBanking$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperForNonAuditedEntitiesTppCertificateInformation>> {
  const rb = new RequestBuilder(rootUrl, getTppCertificateInformationOpenBanking.PATH, 'get');
  if (params) {
    rb.path('certificateTokenHash', params.certificateTokenHash, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperForNonAuditedEntitiesTppCertificateInformation>;
    })
  );
}

getTppCertificateInformationOpenBanking.PATH = '/resources/openapi/untrustedOpenBankingApi/OnlineBankingXs2aService/getTppCertificateInformationOpenBanking/{certificateTokenHash}';
