/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Message } from '../../models/message';
import { MessageSortingAttribute } from '../../models/message-sorting-attribute';
import { MessageSortingDirection } from '../../models/message-sorting-direction';

export interface GetOutboundMessagesForCurrentUser$Params {
  pageIndex: number;
  paginationSize: number;
  sortingAttribute: MessageSortingAttribute;
  sortingDirection: MessageSortingDirection;
}

export function getOutboundMessagesForCurrentUser(http: HttpClient, rootUrl: string, params: GetOutboundMessagesForCurrentUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Message>>> {
  const rb = new RequestBuilder(rootUrl, getOutboundMessagesForCurrentUser.PATH, 'get');
  if (params) {
    rb.path('pageIndex', params.pageIndex, {});
    rb.path('paginationSize', params.paginationSize, {});
    rb.path('sortingAttribute', params.sortingAttribute, {});
    rb.path('sortingDirection', params.sortingDirection, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Message>>;
    })
  );
}

getOutboundMessagesForCurrentUser.PATH = '/resources/openapi/secureOnlineBankingApi/OnlineBankingMessageService/getOutboundMessagesForCurrentUser/{pageIndex}/{paginationSize}/{sortingAttribute}/{sortingDirection}';
