/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentOrder } from '../../models/payment-order';

export interface GetNewOrderFromTemplate$Params {
  orderTemplateUUID: string;
}

export function getNewOrderFromTemplate(http: HttpClient, rootUrl: string, params: GetNewOrderFromTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentOrder>> {
  const rb = new RequestBuilder(rootUrl, getNewOrderFromTemplate.PATH, 'get');
  if (params) {
    rb.path('orderTemplateUUID', params.orderTemplateUUID, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentOrder>;
    })
  );
}

getNewOrderFromTemplate.PATH = '/resources/openapi/secureOnlineBankingApi/OnlineBankingPaymentTemplateService/getNewOrderFromTemplate/{orderTemplateUUID}';
