/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnlineBankingImage } from '../../models/online-banking-image';
import { OnlineBankingImageIdentifier } from '../../models/online-banking-image-identifier';

export interface GetOnlineBankingImage$Params {
  identifier: OnlineBankingImageIdentifier;
}

export function getOnlineBankingImage(http: HttpClient, rootUrl: string, params: GetOnlineBankingImage$Params, context?: HttpContext): Observable<StrictHttpResponse<OnlineBankingImage>> {
  const rb = new RequestBuilder(rootUrl, getOnlineBankingImage.PATH, 'get');
  if (params) {
    rb.path('identifier', params.identifier, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OnlineBankingImage>;
    })
  );
}

getOnlineBankingImage.PATH = '/resources/openapi/untrustedOnlineBankingApi/OnlineBankingImageService/loadImage/{identifier}';
