/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperCollectionForNonAuditedEntitiesTmsUserDevice } from '../../models/dialog-wrapper-collection-for-non-audited-entities-tms-user-device';

export interface GetTmsDevicesForUser1$Params {
}

export function getTmsDevicesForUser1(http: HttpClient, rootUrl: string, params?: GetTmsDevicesForUser1$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperCollectionForNonAuditedEntitiesTmsUserDevice>> {
  const rb = new RequestBuilder(rootUrl, getTmsDevicesForUser1.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperCollectionForNonAuditedEntitiesTmsUserDevice>;
    })
  );
}

getTmsDevicesForUser1.PATH = '/resources/openapi/secureOpenBankingApi/OnlineBankingXs2aService/getTmsDevicesForUser';
