/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IbanPlusLookupResult } from '../../models/iban-plus-lookup-result';

export interface IbanPlusLookup$Params {
  iban: string;
}

export function ibanPlusLookup(http: HttpClient, rootUrl: string, params: IbanPlusLookup$Params, context?: HttpContext): Observable<StrictHttpResponse<IbanPlusLookupResult>> {
  const rb = new RequestBuilder(rootUrl, ibanPlusLookup.PATH, 'get');
  if (params) {
    rb.path('iban', params.iban, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IbanPlusLookupResult>;
    })
  );
}

ibanPlusLookup.PATH = '/resources/openapi/secureOnlineBankingApi/PaymentOrderService/ibanPlusLookup/{iban}';
