/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface IsXs2APaymentRecordPaymentOrderPersisted$Params {
  paymentId: string;
}

export function isXs2APaymentRecordPaymentOrderPersisted(http: HttpClient, rootUrl: string, params: IsXs2APaymentRecordPaymentOrderPersisted$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, isXs2APaymentRecordPaymentOrderPersisted.PATH, 'get');
  if (params) {
    rb.path('paymentId', params.paymentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

isXs2APaymentRecordPaymentOrderPersisted.PATH = '/resources/openapi/secureOpenBankingApi/OnlineBankingXs2aPaymentService/isXs2aPaymentRecordPaymentOrderPersisted/{paymentId}';
