/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnlineBankingSecurityOrderWrapper } from '../../models/online-banking-security-order-wrapper';

export interface LoadSecurityOrderAndSigningStatus$Params {
      body?: Array<string>
}

export function loadSecurityOrderAndSigningStatus(http: HttpClient, rootUrl: string, params?: LoadSecurityOrderAndSigningStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OnlineBankingSecurityOrderWrapper>>> {
  const rb = new RequestBuilder(rootUrl, loadSecurityOrderAndSigningStatus.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OnlineBankingSecurityOrderWrapper>>;
    })
  );
}

loadSecurityOrderAndSigningStatus.PATH = '/resources/openapi/secureOnlineBankingApi/SecurityOrderService/loadSecurityOrderAndSigningStatus';
