/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Portfolio } from '../../models/portfolio';

export interface LoadPortfoliosForSecurityOrders$Params {
      body?: Array<string>
}

export function loadPortfoliosForSecurityOrders(http: HttpClient, rootUrl: string, params?: LoadPortfoliosForSecurityOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: Portfolio;
}>> {
  const rb = new RequestBuilder(rootUrl, loadPortfoliosForSecurityOrders.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: Portfolio;
      }>;
    })
  );
}

loadPortfoliosForSecurityOrders.PATH = '/resources/openapi/secureOnlineBankingApi/SecurityOrderService/loadPortfoliosForSecurityOrders';
