/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperXs2AConsent } from '../../models/dialog-wrapper-xs-2-a-consent';

export interface LoadXs2AConsentOpenBanking$Params {
  consentId: string;
}

export function loadXs2AConsentOpenBanking(http: HttpClient, rootUrl: string, params: LoadXs2AConsentOpenBanking$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperXs2AConsent>> {
  const rb = new RequestBuilder(rootUrl, loadXs2AConsentOpenBanking.PATH, 'get');
  if (params) {
    rb.path('consentId', params.consentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperXs2AConsent>;
    })
  );
}

loadXs2AConsentOpenBanking.PATH = '/resources/openapi/secureOpenBankingApi/OnlineBankingXs2aConsentService/loadXs2aConsentOpenBanking/{consentId}';
