/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImmediateProcessingUiStatusWrapper } from '../../models/immediate-processing-ui-status-wrapper';

export interface LoadXs2AImmediatePaymentStatus$Params {
  paymentId: string;
}

export function loadXs2AImmediatePaymentStatus(http: HttpClient, rootUrl: string, params: LoadXs2AImmediatePaymentStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<ImmediateProcessingUiStatusWrapper>> {
  const rb = new RequestBuilder(rootUrl, loadXs2AImmediatePaymentStatus.PATH, 'get');
  if (params) {
    rb.path('paymentId', params.paymentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImmediateProcessingUiStatusWrapper>;
    })
  );
}

loadXs2AImmediatePaymentStatus.PATH = '/resources/openapi/untrustedOpenBankingApi/OnlineBankingXs2aPaymentService/loadXs2aImmediatePaymentStatus/{paymentId}';
