/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderSigningWrapper } from '../../models/order-signing-wrapper';

export interface LoadSecurityOrders$Params {
}

export function loadSecurityOrders(http: HttpClient, rootUrl: string, params?: LoadSecurityOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderSigningWrapper>>> {
  const rb = new RequestBuilder(rootUrl, loadSecurityOrders.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OrderSigningWrapper>>;
    })
  );
}

loadSecurityOrders.PATH = '/resources/openapi/secureOnlineBankingApi/SecurityOrderService/loadSecurityOrders';
