/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperForNonAuditedEntitiesDocumentWrapper } from '../../models/dialog-wrapper-for-non-audited-entities-document-wrapper';

export interface LoadDocument$Params {
      body?: string
}

export function loadDocument(http: HttpClient, rootUrl: string, params?: LoadDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperForNonAuditedEntitiesDocumentWrapper>> {
  const rb = new RequestBuilder(rootUrl, loadDocument.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperForNonAuditedEntitiesDocumentWrapper>;
    })
  );
}

loadDocument.PATH = '/resources/openapi/secureOnlineBankingApi/OnlineBankingDocumentRepositoryService/loadDocument';
