/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientAccount } from '../../models/client-account';

export interface LoadGiroAccountsWithViewPermission$Params {
}

export function loadGiroAccountsWithViewPermission(http: HttpClient, rootUrl: string, params?: LoadGiroAccountsWithViewPermission$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ClientAccount>>> {
  const rb = new RequestBuilder(rootUrl, loadGiroAccountsWithViewPermission.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ClientAccount>>;
    })
  );
}

loadGiroAccountsWithViewPermission.PATH = '/resources/openapi/secureOnlineBankingApi/AccountInformationService/loadGiroAccountsWithViewPermission';
