/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperForNonAuditedEntitiesXs2APaymentRecordWrapper } from '../../models/dialog-wrapper-for-non-audited-entities-xs-2-a-payment-record-wrapper';

export interface LoadXs2APaymentRecordImmediatePayment$Params {
  paymentId: string;
}

export function loadXs2APaymentRecordImmediatePayment(http: HttpClient, rootUrl: string, params: LoadXs2APaymentRecordImmediatePayment$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperForNonAuditedEntitiesXs2APaymentRecordWrapper>> {
  const rb = new RequestBuilder(rootUrl, loadXs2APaymentRecordImmediatePayment.PATH, 'get');
  if (params) {
    rb.path('paymentId', params.paymentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperForNonAuditedEntitiesXs2APaymentRecordWrapper>;
    })
  );
}

loadXs2APaymentRecordImmediatePayment.PATH = '/resources/openapi/untrustedOpenBankingApi/OnlineBankingXs2aPaymentService/loadXs2aPaymentRecordImmediatePayment/{paymentId}';
