/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PortfolioClientAccounts } from '../../models/portfolio-client-accounts';

export interface LoadSettlementAccountsForRecording$Params {
      body?: Array<string>
}

export function loadSettlementAccountsForRecording(http: HttpClient, rootUrl: string, params?: LoadSettlementAccountsForRecording$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PortfolioClientAccounts>>> {
  const rb = new RequestBuilder(rootUrl, loadSettlementAccountsForRecording.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PortfolioClientAccounts>>;
    })
  );
}

loadSettlementAccountsForRecording.PATH = '/resources/openapi/secureOnlineBankingApi/SecurityOrderService/loadSettlementAccountsForRecording';
