/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnlineBankingBookingLineRequest } from '../../models/online-banking-booking-line-request';
import { OnlineBankingPaymentBookingLineResultWrapper } from '../../models/online-banking-payment-booking-line-result-wrapper';

export interface LoadTransactions$Params {
      body: OnlineBankingBookingLineRequest
}

export function loadTransactions(http: HttpClient, rootUrl: string, params: LoadTransactions$Params, context?: HttpContext): Observable<StrictHttpResponse<OnlineBankingPaymentBookingLineResultWrapper>> {
  const rb = new RequestBuilder(rootUrl, loadTransactions.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OnlineBankingPaymentBookingLineResultWrapper>;
    })
  );
}

loadTransactions.PATH = '/resources/openapi/secureOnlineBankingApi/PaymentBookingLineService/loadTransactions';
