/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperCollectionXs2APiispConsentInformationHolder } from '../../models/dialog-wrapper-collection-xs-2-a-piisp-consent-information-holder';

export interface LoadXs2APiispConsentHolders$Params {
}

export function loadXs2APiispConsentHolders(http: HttpClient, rootUrl: string, params?: LoadXs2APiispConsentHolders$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperCollectionXs2APiispConsentInformationHolder>> {
  const rb = new RequestBuilder(rootUrl, loadXs2APiispConsentHolders.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperCollectionXs2APiispConsentInformationHolder>;
    })
  );
}

loadXs2APiispConsentHolders.PATH = '/resources/openapi/secureOnlineBankingApi/Xs2aConsentService/loadXs2aPiispConsentHolders';
