/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Portfolio } from '../../models/portfolio';

export interface LoadPortfolioAccountsForRecording$Params {
}

export function loadPortfolioAccountsForRecording(http: HttpClient, rootUrl: string, params?: LoadPortfolioAccountsForRecording$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Portfolio>>> {
  const rb = new RequestBuilder(rootUrl, loadPortfolioAccountsForRecording.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Portfolio>>;
    })
  );
}

loadPortfolioAccountsForRecording.PATH = '/resources/openapi/secureOnlineBankingApi/SecurityOrderService/loadPortfolioAccountsForRecording';
