/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperXs2APiispConsentInformationHolder } from '../../models/dialog-wrapper-xs-2-a-piisp-consent-information-holder';

export interface LoadXs2APiispConsentHolder$Params {
  xs2aPiispConsentId: string;
}

export function loadXs2APiispConsentHolder(http: HttpClient, rootUrl: string, params: LoadXs2APiispConsentHolder$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperXs2APiispConsentInformationHolder>> {
  const rb = new RequestBuilder(rootUrl, loadXs2APiispConsentHolder.PATH, 'get');
  if (params) {
    rb.path('xs2aPiispConsentId', params.xs2aPiispConsentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperXs2APiispConsentInformationHolder>;
    })
  );
}

loadXs2APiispConsentHolder.PATH = '/resources/openapi/secureOnlineBankingApi/Xs2aConsentService/loadXs2aPiispConsentHolder/{xs2aPiispConsentId}';
