/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConvertedMoneyAmount } from '../../models/converted-money-amount';

export interface LoadPaymentOrderExchangeRate$Params {
  sourceIsoCurrencyCode: string;
  sourceAmount: number;
  targetIsoCurrencyCode: string;
}

export function loadPaymentOrderExchangeRate(http: HttpClient, rootUrl: string, params: LoadPaymentOrderExchangeRate$Params, context?: HttpContext): Observable<StrictHttpResponse<ConvertedMoneyAmount>> {
  const rb = new RequestBuilder(rootUrl, loadPaymentOrderExchangeRate.PATH, 'get');
  if (params) {
    rb.path('sourceIsoCurrencyCode', params.sourceIsoCurrencyCode, {});
    rb.path('sourceAmount', params.sourceAmount, {});
    rb.path('targetIsoCurrencyCode', params.targetIsoCurrencyCode, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConvertedMoneyAmount>;
    })
  );
}

loadPaymentOrderExchangeRate.PATH = '/resources/openapi/secureOnlineBankingApi/OnlineBankingExchangeRatesService/loadPaymentOrderExchangeRate/{sourceIsoCurrencyCode}/{sourceAmount}/{targetIsoCurrencyCode}';
