/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnlineBankingAccountInformationWrapper } from '../../models/online-banking-account-information-wrapper';

export interface LoadAccountInformation$Params {
  clientAccountUuid: string;
}

export function loadAccountInformation(http: HttpClient, rootUrl: string, params: LoadAccountInformation$Params, context?: HttpContext): Observable<StrictHttpResponse<OnlineBankingAccountInformationWrapper>> {
  const rb = new RequestBuilder(rootUrl, loadAccountInformation.PATH, 'get');
  if (params) {
    rb.path('clientAccountUuid', params.clientAccountUuid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OnlineBankingAccountInformationWrapper>;
    })
  );
}

loadAccountInformation.PATH = '/resources/openapi/secureOnlineBankingApi/AccountInformationService/loadAccountInformation/{clientAccountUuid}';
