/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConvertedMoneyAmount } from '../../models/converted-money-amount';

export interface LoadExchangeRates$Params {
}

export function loadExchangeRates(http: HttpClient, rootUrl: string, params?: LoadExchangeRates$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ConvertedMoneyAmount>>> {
  const rb = new RequestBuilder(rootUrl, loadExchangeRates.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ConvertedMoneyAmount>>;
    })
  );
}

loadExchangeRates.PATH = '/resources/openapi/secureOnlineBankingApi/OnlineBankingExchangeRatesService/loadExchangeRates';
