/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentOrder } from '../../models/payment-order';

export interface LoadPartiallySignedPaymentOrders$Params {
}

export function loadPartiallySignedPaymentOrders(http: HttpClient, rootUrl: string, params?: LoadPartiallySignedPaymentOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PaymentOrder>>> {
  const rb = new RequestBuilder(rootUrl, loadPartiallySignedPaymentOrders.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PaymentOrder>>;
    })
  );
}

loadPartiallySignedPaymentOrders.PATH = '/resources/openapi/secureOnlineBankingApi/PaymentOrderService/loadPartiallySignedPaymentOrders';
