/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperCollectionClientAccount } from '../../models/dialog-wrapper-collection-client-account';

export interface LoadDebitAccountsOpenBanking$Params {
}

export function loadDebitAccountsOpenBanking(http: HttpClient, rootUrl: string, params?: LoadDebitAccountsOpenBanking$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperCollectionClientAccount>> {
  const rb = new RequestBuilder(rootUrl, loadDebitAccountsOpenBanking.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperCollectionClientAccount>;
    })
  );
}

loadDebitAccountsOpenBanking.PATH = '/resources/openapi/secureOpenBankingApi/OnlineBankingXs2aService/loadDebitAccountsOpenBanking';
