/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperCollectionForNonAuditedEntitiesOnlineBankingDerivativesWrapper } from '../../models/dialog-wrapper-collection-for-non-audited-entities-online-banking-derivatives-wrapper';

export interface LoadDerivatives$Params {
}

export function loadDerivatives(http: HttpClient, rootUrl: string, params?: LoadDerivatives$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperCollectionForNonAuditedEntitiesOnlineBankingDerivativesWrapper>> {
  const rb = new RequestBuilder(rootUrl, loadDerivatives.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperCollectionForNonAuditedEntitiesOnlineBankingDerivativesWrapper>;
    })
  );
}

loadDerivatives.PATH = '/resources/openapi/secureOnlineBankingApi/DerivativesService/loadDerivatives';
