/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperForNonAuditedEntitiesDocumentRepositoryResultWrapper } from '../../models/dialog-wrapper-for-non-audited-entities-document-repository-result-wrapper';
import { DocumentRepositoryRequest } from '../../models/document-repository-request';

export interface LoadDocumentList$Params {
      body?: DocumentRepositoryRequest
}

export function loadDocumentList(http: HttpClient, rootUrl: string, params?: LoadDocumentList$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperForNonAuditedEntitiesDocumentRepositoryResultWrapper>> {
  const rb = new RequestBuilder(rootUrl, loadDocumentList.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperForNonAuditedEntitiesDocumentRepositoryResultWrapper>;
    })
  );
}

loadDocumentList.PATH = '/resources/openapi/secureOnlineBankingApi/OnlineBankingDocumentRepositoryService/loadDocumentList';
