/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnlineBankingSecurityOrder } from '../../models/online-banking-security-order';

export interface LoadPartiallySignedSecurityOrders$Params {
}

export function loadPartiallySignedSecurityOrders(http: HttpClient, rootUrl: string, params?: LoadPartiallySignedSecurityOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OnlineBankingSecurityOrder>>> {
  const rb = new RequestBuilder(rootUrl, loadPartiallySignedSecurityOrders.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OnlineBankingSecurityOrder>>;
    })
  );
}

loadPartiallySignedSecurityOrders.PATH = '/resources/openapi/secureOnlineBankingApi/SecurityOrderService/loadPartiallySignedSecurityOrders';
