/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperCollectionClientAccount } from '../../models/dialog-wrapper-collection-client-account';

export interface LoadClientAccountsForXs2AConsent$Params {
  consentId: string;
}

export function loadClientAccountsForXs2AConsent(http: HttpClient, rootUrl: string, params: LoadClientAccountsForXs2AConsent$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperCollectionClientAccount>> {
  const rb = new RequestBuilder(rootUrl, loadClientAccountsForXs2AConsent.PATH, 'get');
  if (params) {
    rb.path('consentId', params.consentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperCollectionClientAccount>;
    })
  );
}

loadClientAccountsForXs2AConsent.PATH = '/resources/openapi/secureOpenBankingApi/OnlineBankingXs2aConsentService/loadClientAccountsForXs2aConsent/{consentId}';
