/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TmsDeviceLockReason } from '../../models/tms-device-lock-reason';

export interface LockTmsDevice$Params {
  deviceId: number;

/**
 * Reason for locking the device (must be a FE_* reason)
 */
  lockReason: TmsDeviceLockReason;
}

export function lockTmsDevice(http: HttpClient, rootUrl: string, params: LockTmsDevice$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, lockTmsDevice.PATH, 'get');
  if (params) {
    rb.path('deviceId', params.deviceId, {});
    rb.path('lockReason', params.lockReason, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

lockTmsDevice.PATH = '/resources/openapi/secureOnlineBankingApi/TwoFactorService/lockTmsDevice/{deviceId}/{lockReason}';
