/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperCollectionPaymentOrder } from '../../models/dialog-wrapper-collection-payment-order';

export interface PersistXs2APaymentRecord$Params {
  paymentId: string;
  debitorAccount: string;
}

export function persistXs2APaymentRecord(http: HttpClient, rootUrl: string, params: PersistXs2APaymentRecord$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperCollectionPaymentOrder>> {
  const rb = new RequestBuilder(rootUrl, persistXs2APaymentRecord.PATH, 'get');
  if (params) {
    rb.path('paymentId', params.paymentId, {});
    rb.path('debitorAccount', params.debitorAccount, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperCollectionPaymentOrder>;
    })
  );
}

persistXs2APaymentRecord.PATH = '/resources/openapi/secureOpenBankingApi/OnlineBankingXs2aPaymentService/persistXs2aPaymentRecord/{paymentId}/{debitorAccount}';
