/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperOnlineBankingSecurityOrder } from '../../models/dialog-wrapper-online-banking-security-order';

export interface PersistSecurityOrder$Params {
      body: DialogWrapperOnlineBankingSecurityOrder
}

export function persistSecurityOrder(http: HttpClient, rootUrl: string, params: PersistSecurityOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperOnlineBankingSecurityOrder>> {
  const rb = new RequestBuilder(rootUrl, persistSecurityOrder.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperOnlineBankingSecurityOrder>;
    })
  );
}

persistSecurityOrder.PATH = '/resources/openapi/secureOnlineBankingApi/SecurityOrderService/persistSecurityOrder';
