/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperXs2AConsent } from '../../models/dialog-wrapper-xs-2-a-consent';

export interface RetrieveXs2AConsentConfirmationUpdate$Params {
}

export function retrieveXs2AConsentConfirmationUpdate(http: HttpClient, rootUrl: string, params?: RetrieveXs2AConsentConfirmationUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperXs2AConsent>> {
  const rb = new RequestBuilder(rootUrl, retrieveXs2AConsentConfirmationUpdate.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperXs2AConsent>;
    })
  );
}

retrieveXs2AConsentConfirmationUpdate.PATH = '/resources/openapi/secureOnlineBankingApi/Xs2aConsentService/retrieveXs2aConsentConfirmationUpdate';
