/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperForNonAuditedEntitiesOnlineBankingBulkOrderProgress } from '../../models/dialog-wrapper-for-non-audited-entities-online-banking-bulk-order-progress';

export interface RetrieveBulkProcessingStatus$Params {
  uuid: string;
}

export function retrieveBulkProcessingStatus(http: HttpClient, rootUrl: string, params: RetrieveBulkProcessingStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperForNonAuditedEntitiesOnlineBankingBulkOrderProgress>> {
  const rb = new RequestBuilder(rootUrl, retrieveBulkProcessingStatus.PATH, 'get');
  if (params) {
    rb.path('uuid', params.uuid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperForNonAuditedEntitiesOnlineBankingBulkOrderProgress>;
    })
  );
}

retrieveBulkProcessingStatus.PATH = '/resources/openapi/secureOnlineBankingApi/BulkUploadService/retrieveBulkProcessingStatus/{uuid}';
