/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperCollectionPaymentOrder } from '../../models/dialog-wrapper-collection-payment-order';

export interface RetrieveXs2APaymentConfirmationUpdate$Params {
}

export function retrieveXs2APaymentConfirmationUpdate(http: HttpClient, rootUrl: string, params?: RetrieveXs2APaymentConfirmationUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperCollectionPaymentOrder>> {
  const rb = new RequestBuilder(rootUrl, retrieveXs2APaymentConfirmationUpdate.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperCollectionPaymentOrder>;
    })
  );
}

retrieveXs2APaymentConfirmationUpdate.PATH = '/resources/openapi/secureOpenBankingApi/OnlineBankingXs2aPaymentService/retrieveXs2aPaymentConfirmationUpdate';
