/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TmsSigningRequestStatus } from '../../models/tms-signing-request-status';

export interface RetrieveAddDeviceConfirmationRequest$Params {
}

export function retrieveAddDeviceConfirmationRequest(http: HttpClient, rootUrl: string, params?: RetrieveAddDeviceConfirmationRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<TmsSigningRequestStatus>> {
  const rb = new RequestBuilder(rootUrl, retrieveAddDeviceConfirmationRequest.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TmsSigningRequestStatus>;
    })
  );
}

retrieveAddDeviceConfirmationRequest.PATH = '/resources/openapi/secureOnlineBankingApi/TwoFactorService/retrieveAddDeviceConfirmationRequest';
