/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperXs2AConsent } from '../../models/dialog-wrapper-xs-2-a-consent';

export interface RetrieveXs2AConsentConfirmationUpdateOpenBanking$Params {
}

export function retrieveXs2AConsentConfirmationUpdateOpenBanking(http: HttpClient, rootUrl: string, params?: RetrieveXs2AConsentConfirmationUpdateOpenBanking$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperXs2AConsent>> {
  const rb = new RequestBuilder(rootUrl, retrieveXs2AConsentConfirmationUpdateOpenBanking.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperXs2AConsent>;
    })
  );
}

retrieveXs2AConsentConfirmationUpdateOpenBanking.PATH = '/resources/openapi/secureOpenBankingApi/OnlineBankingXs2aConsentService/retrieveXs2aConsentConfirmationUpdateOpenBanking';
