/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperForNonAuditedEntitiesBoolean } from '../../models/dialog-wrapper-for-non-audited-entities-boolean';
import { MessageSendingRequest } from '../../models/message-sending-request';

export interface SendMessage$Params {
      body?: MessageSendingRequest
}

export function sendMessage(http: HttpClient, rootUrl: string, params?: SendMessage$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperForNonAuditedEntitiesBoolean>> {
  const rb = new RequestBuilder(rootUrl, sendMessage.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperForNonAuditedEntitiesBoolean>;
    })
  );
}

sendMessage.PATH = '/resources/openapi/secureOnlineBankingApi/OnlineBankingMessageService/sendMessage';
