/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperOnlineBankingAccountConfiguration } from '../../models/dialog-wrapper-online-banking-account-configuration';

export interface SetAccountConfiguration$Params {
  clientAccountUuid: string;
      body?: DialogWrapperOnlineBankingAccountConfiguration
}

export function setAccountConfiguration(http: HttpClient, rootUrl: string, params: SetAccountConfiguration$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperOnlineBankingAccountConfiguration>> {
  const rb = new RequestBuilder(rootUrl, setAccountConfiguration.PATH, 'put');
  if (params) {
    rb.path('clientAccountUuid', params.clientAccountUuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperOnlineBankingAccountConfiguration>;
    })
  );
}

setAccountConfiguration.PATH = '/resources/openapi/secureOnlineBankingApi/AccountConfiguration/{clientAccountUuid}';
