/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserProperty } from '../../models/user-property';

export interface StoreUserProperty$Params {
      body?: UserProperty
}

export function storeUserProperty(http: HttpClient, rootUrl: string, params?: StoreUserProperty$Params, context?: HttpContext): Observable<StrictHttpResponse<UserProperty>> {
  const rb = new RequestBuilder(rootUrl, storeUserProperty.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserProperty>;
    })
  );
}

storeUserProperty.PATH = '/resources/openapi/secureOnlineBankingApi/UserPropertyService/storeUserProperty';
