/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperPaymentOrder } from '../../models/dialog-wrapper-payment-order';
import { OrderTemplate } from '../../models/order-template';

export interface StoreOrderAsTemplate$Params {
      body?: OrderTemplate
}

export function storeOrderAsTemplate(http: HttpClient, rootUrl: string, params?: StoreOrderAsTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperPaymentOrder>> {
  const rb = new RequestBuilder(rootUrl, storeOrderAsTemplate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperPaymentOrder>;
    })
  );
}

storeOrderAsTemplate.PATH = '/resources/openapi/secureOnlineBankingApi/OnlineBankingPaymentTemplateService/storeOrderAsTemplate';
