/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperForNonAuditedEntitiesString } from '../../models/dialog-wrapper-for-non-audited-entities-string';
import { FileAttachement } from '../../models/file-attachement';

export interface UploadBulkOrder$Params {
      body?: FileAttachement
}

export function uploadBulkOrder(http: HttpClient, rootUrl: string, params?: UploadBulkOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperForNonAuditedEntitiesString>> {
  const rb = new RequestBuilder(rootUrl, uploadBulkOrder.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperForNonAuditedEntitiesString>;
    })
  );
}

uploadBulkOrder.PATH = '/resources/openapi/secureOnlineBankingApi/BulkUploadService/uploadBulkOrder';
