/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ValidateXs2AConsentOpenBanking$Params {
  consentId: string;
}

export function validateXs2AConsentOpenBanking(http: HttpClient, rootUrl: string, params: ValidateXs2AConsentOpenBanking$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, validateXs2AConsentOpenBanking.PATH, 'get');
  if (params) {
    rb.path('consentId', params.consentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

validateXs2AConsentOpenBanking.PATH = '/resources/openapi/untrustedOpenBankingApi/OnlineBankingXs2aConsentService/validateXs2aConsentOpenBanking/{consentId}';
