/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DialogWrapperForNonAuditedEntitiesBoolean } from '../../models/dialog-wrapper-for-non-audited-entities-boolean';

export interface ValidateXs2APaymentRecord$Params {
  paymentId: string;
}

export function validateXs2APaymentRecord(http: HttpClient, rootUrl: string, params: ValidateXs2APaymentRecord$Params, context?: HttpContext): Observable<StrictHttpResponse<DialogWrapperForNonAuditedEntitiesBoolean>> {
  const rb = new RequestBuilder(rootUrl, validateXs2APaymentRecord.PATH, 'get');
  if (params) {
    rb.path('paymentId', params.paymentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DialogWrapperForNonAuditedEntitiesBoolean>;
    })
  );
}

validateXs2APaymentRecord.PATH = '/resources/openapi/untrustedOpenBankingApi/OnlineBankingXs2aPaymentService/validateXs2aPaymentRecord/{paymentId}';
