/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AbstractOrder {
  auditUuid: string;
  fullySignedDate?: string;
  orderNumber: string;
  orderType?: string;
  recordingDate: string;
  recordingPartnerLoginId: string;
}
