/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountClass } from '../models/account-class';
export interface AccountClassStrings {
  key?: AccountClass;
  value?: Array<string>;
}
