/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum AccountClass {
  CLIENT_ACCOUNT = 'CLIENT_ACCOUNT',
  PORTFOLIO_ACCOUNT = 'PORTFOLIO_ACCOUNT',
  TERM_DEPOSIT = 'TERM_DEPOSIT'
}
