/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountReferenceIban } from '../models/account-reference-iban';
export interface AccountReferenceTransactions {
  accountReferenceIbans?: Array<AccountReferenceIban>;
  auditUuid: string;
}
