/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum AdditionalServiceInformation {
  ESIGNATURES = 'ESIGNATURES',
  ESEALS = 'ESEALS',
  WEB_AUTHENTICATION = 'WEB_AUTHENTICATION'
}
