/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ServiceInfo } from '../models/service-info';
export interface CertificateToken {
  certificateTokenHash?: string;
  issuerToken?: CertificateToken;
  issuerx500Principal?: string;
  ncaId?: string;
  ncaName?: string;
  ncaRoles?: Array<string>;
  serviceInfos?: Array<ServiceInfo>;
  x509CertificatePEMString?: string;
}
