/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountEntity } from '../models/account-entity';
import { AccountOwnership } from '../models/account-ownership';
import { BusinessProduct } from '../models/business-product';
import { GozoCurrency } from '../models/gozo-currency';
import { Partner } from '../models/partner';
export type ClientAccount = AccountEntity & {
'accountNumber'?: string;
'name'?: string;
'auditUuid'?: string;
'mainAccountHolder'?: Partner;
'businessProduct'?: BusinessProduct;
'description'?: string;
'accountCurrency'?: GozoCurrency;
'iban'?: string;
'accountOwnership'?: AccountOwnership;
} & {
};

