/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ConsentStatus {
  RECEIVED = 'RECEIVED',
  REJECTED = 'REJECTED',
  VALID = 'VALID',
  REVOKEDBYPSU = 'REVOKEDBYPSU',
  EXPIRED = 'EXPIRED',
  TERMINATEDBYTPP = 'TERMINATEDBYTPP'
}
