/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExchangeRate } from '../models/exchange-rate';
import { MoneyAmount } from '../models/money-amount';
export type ConvertedMoneyAmount = MoneyAmount & {
'source'?: MoneyAmount;
'sourceToBaseRate'?: ExchangeRate;
'baseToTargetRate'?: ExchangeRate;
} & {
};

