/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CorrespondentBank {
  intermediaryAccount?: string;
  intermediaryAccountThree?: string;
  intermediaryAccountTwo?: string;
  intermediaryBic?: string;
  intermediaryBicThree?: string;
  intermediaryBicTwo?: string;
}
