/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum DayCountConventionGiro {
  CC_30_E_360_ISDA = 'CC_30E_360_ISDA',
  CC_30_US_360_ISDA = 'CC_30US_360_ISDA',
  CC_ACT_360_ISDA = 'CC_ACT_360_ISDA',
  CC_ACT_365_ISDA = 'CC_ACT_365_ISDA',
  CC_ACT_ACT_ISDA = 'CC_ACT_ACT_ISDA'
}
