/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { OnlineBankingBulkOrderProgress } from '../models/online-banking-bulk-order-progress';
export interface DialogWrapperForNonAuditedEntitiesOnlineBankingBulkOrderProgress {
  businessObject?: OnlineBankingBulkOrderProgress;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
