/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { Xs2ARequestWrapper } from '../models/xs-2-a-request-wrapper';
export interface DialogWrapperForNonAuditedEntitiesXs2ARequestWrapper {
  businessObject?: Xs2ARequestWrapper;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
