/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { OnlineBankingPaymentOrderHistory } from '../models/online-banking-payment-order-history';
export interface DialogWrapperForNonAuditedEntitiesOnlineBankingPaymentOrderHistory {
  businessObject?: OnlineBankingPaymentOrderHistory;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
