/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientAccount } from '../models/client-account';
import { DialogMessage } from '../models/dialog-message';
export interface DialogWrapperCollectionClientAccount {
  businessObject?: Array<ClientAccount>;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
