/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessageSeverityType } from '../models/dialog-message-severity-type';
export interface DialogMessage {
  internalData?: string;
  severity?: DialogMessageSeverityType;
  text?: string;
}
