/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum DialogMessageSeverityType {
  INFO = 'INFO',
  WARNING = 'WARNING',
  IGNORED_WARNING = 'IGNORED_WARNING',
  ERROR = 'ERROR'
}
