/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { Xs2APaymentRecordWrapper } from '../models/xs-2-a-payment-record-wrapper';
export interface DialogWrapperForNonAuditedEntitiesXs2APaymentRecordWrapper {
  businessObject?: Xs2APaymentRecordWrapper;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
