/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { OnlineBankingSecurityOrder } from '../models/online-banking-security-order';
export interface DialogWrapperOnlineBankingSecurityOrder {
  businessObject?: OnlineBankingSecurityOrder;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
