/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { Xs2AConsentInformationHolder } from '../models/xs-2-a-consent-information-holder';
export interface DialogWrapperXs2AConsentInformationHolder {
  businessObject?: Xs2AConsentInformationHolder;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
