/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { OnlineBankingAccountConfiguration } from '../models/online-banking-account-configuration';
export interface DialogWrapperOnlineBankingAccountConfiguration {
  businessObject?: OnlineBankingAccountConfiguration;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
