/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { TmsUserDevice } from '../models/tms-user-device';
export interface DialogWrapperCollectionForNonAuditedEntitiesTmsUserDevice {
  businessObject?: Array<TmsUserDevice>;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
