/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { TppCertificateInformation } from '../models/tpp-certificate-information';
export interface DialogWrapperForNonAuditedEntitiesTppCertificateInformation {
  businessObject?: TppCertificateInformation;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
