/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { Xs2APiispConsentInformationHolder } from '../models/xs-2-a-piisp-consent-information-holder';
export interface DialogWrapperCollectionXs2APiispConsentInformationHolder {
  businessObject?: Array<Xs2APiispConsentInformationHolder>;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
