/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { Xs2APaymentRecord } from '../models/xs-2-a-payment-record';
export interface DialogWrapperForNonAuditedEntitiesXs2APaymentRecord {
  businessObject?: Xs2APaymentRecord;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
