/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { Xs2APiispConsent } from '../models/xs-2-a-piisp-consent';
export interface DialogWrapperXs2APiispConsent {
  businessObject?: Xs2APiispConsent;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
