/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { DocumentWrapper } from '../models/document-wrapper';
export interface DialogWrapperForNonAuditedEntitiesDocumentWrapper {
  businessObject?: DocumentWrapper;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
