/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { OnlineBankingDerivativesWrapper } from '../models/online-banking-derivatives-wrapper';
export interface DialogWrapperCollectionForNonAuditedEntitiesOnlineBankingDerivativesWrapper {
  businessObject?: Array<OnlineBankingDerivativesWrapper>;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
