/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { OnlineBankingBulkOrderCsvLine } from '../models/online-banking-bulk-order-csv-line';
export interface DialogWrapperForNonAuditedEntitiesOnlineBankingBulkOrderCsvLine {
  businessObject?: OnlineBankingBulkOrderCsvLine;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
