/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogMessage } from '../models/dialog-message';
import { Xs2ARequest } from '../models/xs-2-a-request';
export interface DialogWrapperForNonAuditedEntitiesXs2ARequest {
  businessObject?: Xs2ARequest;
  errors?: Array<DialogMessage>;
  ignoredWarnings?: Array<DialogMessage>;
  infos?: Array<DialogMessage>;
  warnings?: Array<DialogMessage>;
}
