/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentType } from '../models/document-type';
import { EntityLinkedFileType } from '../models/entity-linked-file-type';
export interface DocumentRepositoryRequest {
  documentType?: DocumentType;
  documentTypeUuid?: string;
  fromDate?: string;
  pageIndex?: number;
  paginationSize?: number;
  toDate?: string;
  type?: EntityLinkedFileType;
}
