/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentType } from '../models/document-type';
import { EntityLinkedFileType } from '../models/entity-linked-file-type';
export interface DocumentWrapper {
  baseName?: string;
  creationDate?: string;
  documentType?: DocumentType;
  documentTypeUuid?: string;
  extension?: string;
  fileData?: string;
  fileFriendlyName?: string;
  fileUuid?: string;
  hasBeenRead?: boolean;
  sizeInBytes?: number;
  type?: EntityLinkedFileType;
  typeString?: string;
}
