/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GozoCurrency } from '../models/gozo-currency';
export interface ExchangeRate {
  currency: GozoCurrency;
  rate: number;
  rateDate: string;
}
