/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ExportSortingAttribute {
  SORTING_DATE = 'SORTING_DATE',
  MAIN_ACCOUNT_NAME = 'MAIN_ACCOUNT_NAME',
  MAIN_ACCOUNT_NUMBER = 'MAIN_ACCOUNT_NUMBER',
  ACCOUNT_NUMBER = 'ACCOUNT_NUMBER',
  ACCOUNT_TYPE = 'ACCOUNT_TYPE',
  RECORD_TYPE = 'RECORD_TYPE'
}
