/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DateIntervalSelector } from '../models/date-interval-selector';
import { ExportRecordType } from '../models/export-record-type';
import { ExportSortingAttribute } from '../models/export-sorting-attribute';
import { FileType } from '../models/file-type';
import { MainAccountHolderAndAccountsWrapper } from '../models/main-account-holder-and-accounts-wrapper';
import { Partner } from '../models/partner';
import { SortingDirection } from '../models/sorting-direction';
import { SupportedExportRecordType } from '../models/supported-export-record-type';
export interface ExportRequest {
  clientAccounts: Array<string>;
  dateRange?: DateIntervalSelector;
  exportDeposit?: boolean;
  exportGiro?: boolean;
  exportRecordTypes: Array<ExportRecordType>;
  exportSecurities?: boolean;
  exportSortingAttributes: Array<ExportSortingAttribute>;
  fileType?: FileType;
  mainAccountHolder: Array<Partner>;
  mainAccountHolderAndAccountsWrapper?: MainAccountHolderAndAccountsWrapper;
  portfolios: Array<string>;
  requestDate?: string;
  sortingDirection?: SortingDirection;
  supportedExportRecordTypes: Array<SupportedExportRecordType>;
  termDeposits: Array<string>;
}
