/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IbanDbEntry {
  countryName: string;
  ibanBic: string;
  ibanIsoCountryCode: string;
  ibanNationalId: string;
  institutionName: string;
  isoCountryCode: string;
  routingBic?: string;
}
