/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImmediateProcessingUiStatus } from '../models/immediate-processing-ui-status';
export interface ImmediateProcessingUiStatusWrapper {
  message?: string;
  status?: ImmediateProcessingUiStatus;
}
