/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ImmediateProcessingUiStatus {
  NO_IMMEDIATE_PROCESSING = 'NO_IMMEDIATE_PROCESSING',
  PROCESSING = 'PROCESSING',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS'
}
