/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientAccount } from '../models/client-account';
export interface LocalParty {
  feeAccount?: ClientAccount;
  name: string;
  settlementAccount?: ClientAccount;
}
