/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientAccount } from '../models/client-account';
import { OnlineBankingTermDepositDetails } from '../models/online-banking-term-deposit-details';
import { Partner } from '../models/partner';
import { Portfolio } from '../models/portfolio';
export interface MainAccountHolderAndAccountsWrapper {
  clientAccounts?: Array<ClientAccount>;
  mainAccountHolder?: Array<Partner>;
  onlineBankingTermDepositDetails?: Array<OnlineBankingTermDepositDetails>;
  portfolios?: Array<Portfolio>;
}
