/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum MessageSortingAttribute {
  SUBJECT = 'SUBJECT',
  SENDING_DATE = 'SENDING_DATE',
  SENDER_RECEIVER = 'SENDER_RECEIVER',
  RECIPIENT = 'RECIPIENT'
}
