/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageAttachment } from '../models/message-attachment';
export interface MessageSendingRequest {
  attachments?: Array<MessageAttachment>;
  body?: string;
  recipientName?: string;
  recipientUuid?: string;
  subject?: string;
}
