/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageAttachment {
  auditUuid?: string;
  baseName?: string;
  extension?: string;
  fileData?: string;
  isInfected?: boolean;
  mimeType?: string;
  sizeInBytes?: number;
}
