/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageAttachment } from '../models/message-attachment';
export interface Message {
  attachments?: Array<MessageAttachment>;
  auditUuid?: string;
  body?: string;
  deleted?: boolean;
  deletionDate?: string;
  isAcknowledged?: boolean;
  isInboundMessage?: boolean;
  messageDate?: string;
  needsAcknowledgement?: boolean;
  readDate?: string;
  recipientName?: string;
  senderAddress?: string;
  senderName?: string;
  subject?: string;
}
