/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OnlineBankingBulkOrderLineWrapper } from '../models/online-banking-bulk-order-line-wrapper';
import { OnlineBankingBulkProcessingState } from '../models/online-banking-bulk-processing-state';
export interface OnlineBankingBulkOrderProgress {
  bulkUploadUuid: string;
  currentState?: OnlineBankingBulkProcessingState;
  errors?: boolean;
  finishTime?: string;
  finishedPercent?: number;
  orderCount?: number;
  orders?: Array<OnlineBankingBulkOrderLineWrapper>;
  originalFileName?: string;
  startTime?: string;
  userDecidedToIgnoreAllWarnings?: boolean;
}
