/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExchangeRate } from '../models/exchange-rate';
import { MoneyAmount } from '../models/money-amount';
import { OnlineBankingAccountInformationWrapper } from '../models/online-banking-account-information-wrapper';
export interface OnlineBankingTermDepositDetails {
  accountToReportingCcyExchangeRate?: ExchangeRate;
  accruedInterestsInAccountCurrency?: MoneyAmount;
  accruedInterestsInBaseCurrency?: MoneyAmount;
  accruedInterestsInReportingCurrency?: MoneyAmount;
  backingAccount?: OnlineBankingAccountInformationWrapper;
  name?: string;
  onlineBankingProductName?: string;
  termDepositAuditUuid?: string;
  termDepositNumber?: string;
}
