/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum OnlineBankingPaymentOrderStatus {
  CANCELLED = 'CANCELLED',
  IN_PROGRESS = 'IN_PROGRESS',
  RECORDED = 'RECORDED',
  TEMPLATE = 'TEMPLATE',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED'
}
