/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GozoCurrency } from '../models/gozo-currency';
import { MoneyAmount } from '../models/money-amount';
import { OnlineBankingDerivativesFeeWrapper } from '../models/online-banking-derivatives-fee-wrapper';
import { PaymentOrder } from '../models/payment-order';
export interface OnlineBankingDerivativesWrapper {
  currencyPair?: string;
  fees?: Array<OnlineBankingDerivativesFeeWrapper>;
  localValueDate?: string;
  order?: PaymentOrder;
  paymentOrderId?: string;
  principalAccountCcy?: GozoCurrency;
  principalAccountName?: string;
  principalAccountNumber?: string;
  principalAmount?: MoneyAmount;
  settlementAccountCcy?: GozoCurrency;
  settlementAccountName?: string;
  settlementAccountNumber?: string;
  tradeDate?: string;
}
