/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GozoCurrency } from '../models/gozo-currency';
import { OnlineBankingPaymentOrderStatus } from '../models/online-banking-payment-order-status';
import { PaymentChannel } from '../models/payment-channel';
export interface OnlineBankingPaymentOrderHistoryRecord {
  bookingDate?: string;
  channel?: PaymentChannel;
  creationDate?: string;
  instructedAmount?: number;
  instructedCurrency?: GozoCurrency;
  narrativeLine1?: string;
  narrativeLine2?: string;
  narrativeLine3?: string;
  narrativeLine4?: string;
  narrativeLine5?: string;
  narrativeLine6?: string;
  orderAuditUuid?: string;
  orderNumber?: string;
  remotePartyAccountNumber?: string;
  remotePartyName?: string;
  settlementAccountNumber?: string;
  status?: OnlineBankingPaymentOrderStatus;
}
