/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OnlineBankingPaymentTransactionLimitScope } from '../models/online-banking-payment-transaction-limit-scope';
import { OnlineBankingPaymentTransactionType } from '../models/online-banking-payment-transaction-type';
export interface OnlineBankingPaymentTransactionLimit {
  maxAmountBaseCurrency: number;
  scope: OnlineBankingPaymentTransactionLimitScope;
  type: OnlineBankingPaymentTransactionType;
}
