/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OnlineBankingImageIdentifier } from '../models/online-banking-image-identifier';
export interface OnlineBankingImage {
  auditUuid: string;
  description: string;
  height: number;
  identifier: OnlineBankingImageIdentifier;
  image?: string;
  imageFileType?: string;
  scriptCode?: string;
  updateDate: string;
  url?: string;
  width: number;
}
