/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AbstractOrder } from '../models/abstract-order';
import { LimitUntilType } from '../models/limit-until-type';
import { SecurityIdentificationType } from '../models/security-identification-type';
import { SecurityQuantityType } from '../models/security-quantity-type';
import { TradingActionType } from '../models/trading-action-type';
import { TradingOrderType } from '../models/trading-order-type';
export type OnlineBankingSecurityOrder = AbstractOrder & {
'settlementClientAccountNumber'?: string;
'portfolioAccountNumber'?: string;
'securityName'?: string;
'quantity'?: number;
'securityCurrency'?: string;
'identification'?: string;
'limitPerUnit'?: number;
'limitValidUntil'?: string;
'executionVenue'?: string;
'additionalInformation'?: string;
'securitiesIdentificationType'?: SecurityIdentificationType;
'securitiesQuantityType'?: SecurityQuantityType;
'tradingActionType'?: TradingActionType;
'tradingOrderType'?: TradingOrderType;
'limitUntilType'?: LimitUntilType;
} & {
};

