/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientAccount } from '../models/client-account';
import { OnlineBankingAccountConfigurationStatus } from '../models/online-banking-account-configuration-status';
import { OnlineBankingPaymentTransactionLimit } from '../models/online-banking-payment-transaction-limit';
export interface OnlineBankingAccountConfiguration {
  auditUuid: string;
  clientAccount: ClientAccount;
  clientAccountAuditUuid: string;
  status: OnlineBankingAccountConfigurationStatus;
  transactionLimits: Array<OnlineBankingPaymentTransactionLimit>;
  verificationOfPayeeOptedOut?: boolean;
}
