/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BalanceType } from '../models/balance-type';
import { ExchangeRate } from '../models/exchange-rate';
import { MoneyAmount } from '../models/money-amount';
export interface OnlineBankingBalanceWrapper {
  accountToReportingCcyExchangeRate?: ExchangeRate;
  bookingDateBalanceInAccountCurrency?: MoneyAmount;
  bookingDateBalanceInBaseCurrency?: MoneyAmount;
  bookingDateBalanceInReportingCurrency?: MoneyAmount;
  date?: string;
  type?: BalanceType;
  updateBookingDate?: string;
  valueDateBalanceInAccountCurrency?: MoneyAmount;
  valueDateBalanceInBaseCurrency?: MoneyAmount;
  valueDateBalanceInReportingCurrency?: MoneyAmount;
}
