/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OnlineBankingBookingLineRequest {
  fromDate: string;
  givenAccountUuid: string;
  includeBalances: boolean;
  pageIndex: number;
  paginationSize: number;
  sortDescending: boolean;
  toDate: string;
}
