/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OnlineBankingPaymentBookingLineType } from '../models/online-banking-payment-booking-line-type';
export interface OnlineBankingPaymentBookingLine {
  accountCurrency?: string;
  accountIban?: string;
  accountNumber?: string;
  accountType?: string;
  additionalText?: string;
  amountInAccountCurrency?: number;
  amountInBaseCurrency?: number;
  amountInTransactionCurrency?: number;
  auditUuid?: string;
  bookingDate?: string;
  bookingNumber?: number;
  bulkPayment?: boolean;
  fullReferenceNumber?: string;
  isCredit?: boolean;
  otherPartyAccountNumber?: string;
  otherPartyName?: string;
  paymentDetailInfo?: string;
  paymentDetailInfoDigest?: string;
  paymentOrderActionNumber?: string;
  paymentOrderNumber?: string;
  referenceNumber?: number;
  transactionCurrency?: string;
  transactionReference?: string;
  transactionType?: string;
  type?: OnlineBankingPaymentBookingLineType;
  valueDate?: string;
  voucherNumber?: number;
}
