/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OnlineBankingSecurityOrder } from '../models/online-banking-security-order';
import { OrderSigningStatus } from '../models/order-signing-status';
export interface OnlineBankingSecurityOrderWrapper {
  orderStatus?: OrderSigningStatus;
  securityOrder?: OnlineBankingSecurityOrder;
}
