/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientAccount } from '../models/client-account';
import { ExchangeRate } from '../models/exchange-rate';
import { GozoCurrency } from '../models/gozo-currency';
import { MoneyAmount } from '../models/money-amount';
import { OnlineBankingBalanceWrapper } from '../models/online-banking-balance-wrapper';
export interface OnlineBankingAccountInformationWrapper {
  accountCurrency?: GozoCurrency;
  accountToReportingCcyExchangeRate?: ExchangeRate;
  availableBalanceInAccountCurrency?: MoneyAmount;
  availableBalanceInBaseCurrency?: MoneyAmount;
  availableBalanceInReportingCurrency?: MoneyAmount;
  clientAccount?: ClientAccount;
  endOfDayBalance?: OnlineBankingBalanceWrapper;
  intraDayBalance?: OnlineBankingBalanceWrapper;
  reportingCurrency?: GozoCurrency;
}
