/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OnlineBankingPaymentOrderHistorySorting } from '../models/online-banking-payment-order-history-sorting';
import { OnlineBankingPaymentOrderStatus } from '../models/online-banking-payment-order-status';
export interface OnlineBankingPaymentOrderHistoryRequest {
  fromDate?: string;
  pageNumber?: number;
  settlementAccountUuid?: string;
  sortOrder?: OnlineBankingPaymentOrderHistorySorting;
  statuses?: Array<OnlineBankingPaymentOrderStatus>;
  toDate?: string;
}
