/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum OnlineBankingImageIdentifier {
  FAVICON = 'FAVICON',
  MAIN_PAGE_HEADER = 'MAIN_PAGE_HEADER',
  MAIN_PAGE_FOOTER = 'MAIN_PAGE_FOOTER',
  TRACKER_PIXEL = 'TRACKER_PIXEL'
}
