/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DialogWrapperForNonAuditedEntitiesOnlineBankingBulkOrderCsvLine } from '../models/dialog-wrapper-for-non-audited-entities-online-banking-bulk-order-csv-line';
import { DialogWrapperPaymentOrder } from '../models/dialog-wrapper-payment-order';
export interface OnlineBankingBulkOrderLineWrapper {
  bulkOrderCsvLine?: DialogWrapperForNonAuditedEntitiesOnlineBankingBulkOrderCsvLine;
  paymentOrder?: DialogWrapperPaymentOrder;
}
