/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum OnlineBankingAccountConfigurationStatus {
  NEW = 'NEW',
  ACTIVE = 'ACTIVE',
  APPROVAL_PENDING = 'APPROVAL_PENDING',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED'
}
