/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OnlineBankingPaymentOrderHistoryRecord } from '../models/online-banking-payment-order-history-record';
import { OnlineBankingPaymentOrderHistoryRequest } from '../models/online-banking-payment-order-history-request';
export interface OnlineBankingPaymentOrderHistory {
  pageSize?: number;
  records?: Array<OnlineBankingPaymentOrderHistoryRecord>;
  request?: OnlineBankingPaymentOrderHistoryRequest;
  totalPageCount?: number;
  totalRecordCount?: number;
}
