/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MoneyAmount } from '../models/money-amount';
export interface OnlineBankingDerivativesFeeWrapper {
  feeText?: string;
  settledAmountInBaseCcy?: MoneyAmount;
  settledAmountInFeeCcy?: MoneyAmount;
  settledFeePercentage?: number;
}
