/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentOrder } from '../models/payment-order';
export interface OrderTemplate {
  auditUuid: string;
  bluePrint: PaymentOrder;
  name: string;
  relatedAccount: string;
}
