/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountClass } from '../models/account-class';
import { OnlineBankingSecurityOrder } from '../models/online-banking-security-order';
import { PaymentOrder } from '../models/payment-order';
export interface OrderSigningWrapper {
  isActivePartnerAllowedToDelete?: boolean;
  isActivePartnerAllowedToSign?: boolean;
  paymentOrder?: PaymentOrder;
  securityOrder?: OnlineBankingSecurityOrder;
  type?: AccountClass;
}
