/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GozoCurrency } from '../models/gozo-currency';
export interface Partner {
  auditUuid: string;
  baseCurrency?: GozoCurrency;
  name1: string;
  name2?: string;
  partnerId: number;
}
