/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentOnlineBankingStatus {
  deletionDate?: string;
  fullySigned?: boolean;
  fullySignedDate?: string;
  initiatedByTpp?: boolean;
}
