/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CorrespondentBank } from '../models/correspondent-bank';
import { GozoCurrency } from '../models/gozo-currency';
import { LocalParty } from '../models/local-party';
import { PaymentChannel } from '../models/payment-channel';
import { PaymentChargingMode } from '../models/payment-charging-mode';
import { PaymentFlow } from '../models/payment-flow';
import { PaymentOnlineBankingStatus } from '../models/payment-online-banking-status';
import { PaymentRiskRatingResult } from '../models/payment-risk-rating-result';
import { PaymentVariant } from '../models/payment-variant';
import { RemoteParty } from '../models/remote-party';
import { RemotePartyBank } from '../models/remote-party-bank';
import { Xs2APaymentRecord } from '../models/xs-2-a-payment-record';
export interface PaymentOrder {
  auditUuid: string;
  channel?: PaymentChannel;
  chargingMode?: PaymentChargingMode;
  correspondentBank?: CorrespondentBank;
  creationDate: string;
  flow: PaymentFlow;
  foreignPaymentReference?: string;
  instructedAmount?: number;
  instructedCurrency?: GozoCurrency;
  localParty?: LocalParty;
  narrativeLine1?: string;
  narrativeLine2?: string;
  narrativeLine3?: string;
  narrativeLine4?: string;
  narrativeLine5?: string;
  narrativeLine6?: string;
  onlineBankingOrderStatus?: string;
  orderNumber: string;
  paymentOnlineBankingStatus?: PaymentOnlineBankingStatus;
  paymentVariant: PaymentVariant;
  remoteParty?: RemoteParty;
  remotePartyBank?: RemotePartyBank;
  riskRatingResult?: PaymentRiskRatingResult;
  sameDayValue?: boolean;
  urgent?: boolean;
  xs2aPaymentRecord?: Xs2APaymentRecord;
}
