/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum PaymentChannel {
  INTERNAL = 'INTERNAL',
  SWIFT = 'SWIFT',
  SWIFT_CBPR_PLUS = 'SWIFT_CBPR_PLUS',
  SEPA = 'SEPA',
  SEPA_INST = 'SEPA_INST',
  TARGET_2 = 'TARGET2',
  CHAPS = 'CHAPS'
}
