/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentStatusEvent {
  eventClass?: string;
  eventTimestamp?: string;
  infoText?: string;
  paymentOrderActionType?: string;
  paymentOrderNumber?: string;
  paymentOrderStatus?: string;
  paymentOrderUuid?: string;
  settlementAccountUuid?: string;
  type?: string;
}
