/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderSigningStatus } from '../models/order-signing-status';
import { PaymentOrder } from '../models/payment-order';
export interface PaymentOrderWrapper {
  orderStatus?: OrderSigningStatus;
  paymentOrder?: PaymentOrder;
}
