/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentRiskRatingDetail {
  counterpartyAgentBic?: string;
  counterpartyIban?: string;
  counterpartyName?: string;
}
