/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum PaymentVariant {
  CUSTOMER_TRANSFER = 'CUSTOMER_TRANSFER',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  BANK_TO_BANK_TRANSFER = 'BANK_TO_BANK_TRANSFER',
  FX_FORWARD = 'FX_FORWARD',
  FX_SPOT = 'FX_SPOT'
}
