/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountEntity } from '../models/account-entity';
import { GozoCurrency } from '../models/gozo-currency';
import { Partner } from '../models/partner';
import { PortfolioBusinessProduct } from '../models/portfolio-business-product';
export type Portfolio = AccountEntity & {
'auditUuid'?: string;
'accountNumber'?: string;
'name'?: string;
'description'?: string;
'currency'?: GozoCurrency;
'accountHolder'?: Partner;
'businessProduct'?: PortfolioBusinessProduct;
} & {
};

