/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GozoCurrency } from '../models/gozo-currency';
import { MoneyAmount } from '../models/money-amount';
import { PortfolioDrilldownGroupValues } from '../models/portfolio-drilldown-group-values';
import { SecuritiesTransaction } from '../models/securities-transaction';
import { Security } from '../models/security';
export interface PortfolioDrilldownGroup {
  currency: GozoCurrency;
  displayString: string;
  security: Security;
  transactions?: Array<SecuritiesTransaction>;
  valuesBaseCurrency: PortfolioDrilldownGroupValues;
  valuesDrilldownCurrency: PortfolioDrilldownGroupValues;
  valuesPortfolioCurrency: PortfolioDrilldownGroupValues;
  valuesReportingCurrency?: MoneyAmount;
}
