/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GozoCurrency } from '../models/gozo-currency';
export interface PortfolioSummaryValues {
  currency: GozoCurrency;
  gainLoss?: number;
  portfolioValue: number;
}
