/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientAccount } from '../models/client-account';
import { Portfolio } from '../models/portfolio';
export interface PortfolioClientAccounts {
  key?: Portfolio;
  value?: Array<ClientAccount>;
}
