/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PortfolioSummary } from '../models/portfolio-summary';
export interface PortfolioSummaryWrapper {
  cacheStillValid?: boolean;
  hash?: string;
  portfolioSummary?: PortfolioSummary;
}
