/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MoneyAmount } from '../models/money-amount';
import { Portfolio } from '../models/portfolio';
import { PortfolioBusinessProduct } from '../models/portfolio-business-product';
import { PortfolioDrilldownGroup } from '../models/portfolio-drilldown-group';
import { PortfolioSummaryValues } from '../models/portfolio-summary-values';
import { Security } from '../models/security';
export interface PortfolioSummary {
  accountName: string;
  accountNumber: string;
  drilldowns: Array<PortfolioDrilldownGroup>;
  portfolio: Portfolio;
  portfolioBusinessProduct: PortfolioBusinessProduct;
  security?: Security;
  valuesBaseCurrency: PortfolioSummaryValues;
  valuesPortfolioCurrency: PortfolioSummaryValues;
  valuesReportingCurrency?: MoneyAmount;
}
