/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GozoCurrency } from '../models/gozo-currency';
export interface PortfolioDrilldownGroupValues {
  actualPrice: number;
  actualValue: number;
  costPrice?: number;
  costValue?: number;
  currency: GozoCurrency;
  gainLoss?: number;
  nominal: number;
  priceDate: string;
  yieldTotal?: number;
}
