/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdditionalServiceInformation } from '../models/additional-service-information';
export interface QtspAdditionalServiceInfo {
  auditUuid: string;
  information: AdditionalServiceInformation;
}
