/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ServiceQualification } from '../models/service-qualification';
export interface QtspServiceQualifier {
  auditUuid: string;
  qualifier: ServiceQualification;
}
