/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GozoCountry } from '../models/gozo-country';
import { RemotePartyAccountType } from '../models/remote-party-account-type';
export interface RemoteParty {
  account?: string;
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  country?: GozoCountry;
  name?: string;
  remotePartyAccountType?: RemotePartyAccountType;
}
