/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GozoCountry } from '../models/gozo-country';
import { PartyIdentifierType } from '../models/party-identifier-type';
export interface RemotePartyBank {
  country?: GozoCountry;
  identifier?: string;
  identifierType?: PartyIdentifierType;
  name1?: string;
  name2?: string;
}
