/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountReferenceIban } from '../models/account-reference-iban';
export interface RetrieveConsentTripple {
  accounts?: Array<AccountReferenceIban>;
  balances?: Array<AccountReferenceIban>;
  transactions?: Array<AccountReferenceIban>;
}
