/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientAccount } from '../models/client-account';
import { GozoCurrency } from '../models/gozo-currency';
import { SecuritiesCharges } from '../models/securities-charges';
import { SecuritiesIncome } from '../models/securities-income';
import { SecuritiesOrder } from '../models/securities-order';
import { SecuritiesOrderClass } from '../models/securities-order-class';
import { SecuritiesTransactionMode } from '../models/securities-transaction-mode';
import { SecuritiesTransactionStatus } from '../models/securities-transaction-status';
export interface SecuritiesTransaction {
  auditUuid: string;
  bookingDate?: string;
  charges?: Array<SecuritiesCharges>;
  costValueInTradeCurrency?: number;
  executedNominal: number;
  executedPriceInPositionCurrency?: number;
  executedPriceInTradeCurrency?: number;
  income?: Array<SecuritiesIncome>;
  mode: SecuritiesTransactionMode;
  order: SecuritiesOrder;
  orderClass: SecuritiesOrderClass;
  partnerSettlementAccount?: ClientAccount;
  settlementDate: string;
  status: SecuritiesTransactionStatus;
  tradeDate: string;
  tradingCurrency: GozoCurrency;
  transactionNumber?: number;
}
