/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum SecurityClass {
  BOND = 'BOND',
  FUND = 'FUND',
  EQUITY = 'EQUITY',
  BOND_OTHER = 'BOND_OTHER',
  EQUITY_OTHER = 'EQUITY_OTHER'
}
