/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GozoCurrency } from '../models/gozo-currency';
import { MarketIdentifierCode } from '../models/market-identifier-code';
import { SecuritiesCorporateActionPositionItem } from '../models/securities-corporate-action-position-item';
import { Security } from '../models/security';
export interface SecuritiesOrder {
  clientFacingName: string;
  corporateActionPositionItem?: SecuritiesCorporateActionPositionItem;
  mic: MarketIdentifierCode;
  security: Security;
  tradingCurrency: GozoCurrency;
}
