/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SecuritiesCorporateAction } from '../models/securities-corporate-action';
import { SecuritiesCorporateActionIncomeDetails } from '../models/securities-corporate-action-income-details';
export interface SecuritiesCorporateActionDepositoryGroup {
  corporateAction: SecuritiesCorporateAction;
  incomeDetails?: SecuritiesCorporateActionIncomeDetails;
}
