/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GozoCurrency } from '../models/gozo-currency';
import { PriceBase } from '../models/price-base';
import { SecurityClass } from '../models/security-class';
import { SecurityInterestRate } from '../models/security-interest-rate';
import { SecurityType } from '../models/security-type';
export interface Security {
  auditUuid: string;
  dayCountConventionOnlineBanking?: string;
  firstCouponPaymentDate?: string;
  interestRates?: Array<SecurityInterestRate>;
  isin: string;
  longName: string;
  nominalCurrency: GozoCurrency;
  priceBase: PriceBase;
  securityClass: SecurityClass;
  securityType: SecurityType;
  shortName: string;
}
