/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SecuritiesCorporateActionDepositoryGroup } from '../models/securities-corporate-action-depository-group';
export interface SecuritiesCorporateActionPositionItem {
  amount: number;
  depositoryGroup: SecuritiesCorporateActionDepositoryGroup;
  foreignTax: number;
}
