/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum SecurityQuantityType {
  UNITS_NOMINAL = 'UNITS_NOMINAL',
  VALUE = 'VALUE',
  MONETARY_VALUE = 'MONETARY_VALUE'
}
