/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum SecuritiesOrderClass {
  BUY = 'BUY',
  CORPORATE_ACTION = 'CORPORATE_ACTION',
  REDEMPTION = 'REDEMPTION',
  SELL = 'SELL',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT'
}
