/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SecuritiesIncomeStatus } from '../models/securities-income-status';
export interface SecuritiesIncome {
  amountInTradeCurrency?: number;
  bookingDate?: string;
  dividendPerUnit?: number;
  incomeTransactionNumber?: number;
  interestEndDate?: string;
  interestRate?: number;
  interestStartDate?: string;
  settledInterestDays?: number;
  settledInterestFactor?: number;
  status: SecuritiesIncomeStatus;
}
