/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QtspAdditionalServiceInfo } from '../models/qtsp-additional-service-info';
import { QtspServiceQualifier } from '../models/qtsp-service-qualifier';
export interface ServiceInfoStatus {
  additionalServiceInfoUris?: Array<QtspAdditionalServiceInfo>;
  endDate?: string;
  serviceType?: QtspServiceQualifier;
  startDate?: string;
  status?: string;
}
