/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ServiceInfoStatus } from '../models/service-info-status';
export interface ServiceInfo {
  serviceInfoStatus?: Array<ServiceInfoStatus>;
  serviceName?: string;
  trustedListCountryCode?: string;
  tspElectronicAddress?: string;
  tspName?: string;
  tspPostalAddress?: string;
  tspRegistrationIdentifier?: string;
  tspTradeName?: string;
}
