/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CertificateToken } from '../models/certificate-token';
export interface StoredCertificateToken {
  auditUuid: string;
  certificateToken?: CertificateToken;
  certificateTokenHash: string;
  notAfterDate: string;
  notBeforeDate: string;
}
