/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountType } from '../models/account-type';
import { ExportRecordType } from '../models/export-record-type';
export interface SupportedExportRecordType {
  accountType?: AccountType;
  supportedRecordTypes?: Array<ExportRecordType>;
}
