/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountEntity } from '../models/account-entity';
import { DayCountConventionGiro } from '../models/day-count-convention-giro';
import { GozoCurrency } from '../models/gozo-currency';
import { OnlineBankingTermDepositDetails } from '../models/online-banking-term-deposit-details';
export type TermDeposit = AccountEntity & {
'auditUuid'?: string;
'termDepositNumber'?: string;
'name'?: string;
'termDepositCurrency'?: GozoCurrency;
'amount'?: number;
'interestRate'?: number;
'startDate'?: string;
'maturityDate'?: string;
'dayCountConvention'?: DayCountConventionGiro;
'interestAmountAtMaturity'?: number;
'onlineBankingTermDepositDetails'?: OnlineBankingTermDepositDetails;
} & {
};

