/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TmsDeviceLockReason } from '../models/tms-device-lock-reason';
export interface TmsUserDevice {
  appVersion?: string;
  deviceClass?: string;
  deviceId?: number;
  deviceName?: string;
  deviceRisks?: string;
  lastLogin?: string;
  lockReason?: TmsDeviceLockReason;
  locked?: boolean;
  model?: string;
  osVersion?: string;
  serialNumber?: string;
  vendor?: string;
}
