/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TppCertificateInformation {
  certificateSerialNumber?: string;
  certificateTokenHash?: string;
  country?: string;
  hasRoleAccountInformation?: boolean;
  hasRoleAccountServicing?: boolean;
  hasRoleIssuingOfCardBasedPaymentInstruments?: boolean;
  hasRolePaymentInitiation?: boolean;
  locality?: string;
  organization?: string;
  organizationIdentifier?: string;
  postalcode?: string;
  psd2Regulator?: string;
  street?: string;
}
