/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StoredCertificateToken } from '../models/stored-certificate-token';
import { TppStatus } from '../models/tpp-status';
export interface TppListEntry {
  auditUuid: string;
  status: TppStatus;
  storedCertificateToken: StoredCertificateToken;
}
