/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TppCertificateInformationWrapper {
  certificateSerialNumber?: string;
  country?: string;
  hasRoleAccountInformation?: boolean;
  hasRoleAccountServicing?: boolean;
  hasRoleIssuingOfCardBasedPaymentInstruments?: boolean;
  hasRolePaymentInitiation?: boolean;
  organization?: string;
  organizationIdentifier?: string;
  street?: string;
}
