/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum TradingActionType {
  BUY = 'BUY',
  SELL = 'SELL',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
  CANCELLATION = 'CANCELLATION'
}
