/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum TradingOrderType {
  NOT_SET = 'NOT_SET',
  MARKET_ORDER = 'MARKET_ORDER',
  STOP_LOSS_ORDER = 'STOP_LOSS_ORDER',
  LIMIT_ORDER = 'LIMIT_ORDER'
}
