/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserPropertyKey } from '../models/user-property-key';
export interface UserProperty {
  auditUuid: string;
  login?: string;
  propertyKey: UserPropertyKey;
  propertyValue: string;
}
