/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TppListEntry } from '../models/tpp-list-entry';
export interface Xs2APiispConsent {
  auditUuid: string;
  consentId?: string;
  creationDate: string;
  deletionDate?: string;
  isFullySigned?: boolean;
  isPartiallySigned?: boolean;
  relatedIban?: string;
  relatedTpp: TppListEntry;
  tppCertificateTokenHash?: string;
}
