/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum Xs2APaymentRecordType {
  SEPA = 'SEPA',
  SEPA_INST = 'SEPA_INST',
  NONSEPA_IBAN = 'NONSEPA_IBAN',
  NONSEPA_ACCOUNT_NUMBER = 'NONSEPA_ACCOUNT_NUMBER'
}
