/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Xs2APiispConsentDataLine {
  canBeConfirmed?: boolean;
  canBeDeleted?: boolean;
  consentId?: string;
  fullySigned?: boolean;
  grantingDate?: string;
  iban?: string;
}
