/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Xs2APaymentRecord } from '../models/xs-2-a-payment-record';
import { Xs2ARequestStatus } from '../models/xs-2-a-request-status';
export interface Xs2ARequest {
  bulkDeleted?: boolean;
  bulkDeletionDate?: string;
  bulkInvalid?: boolean;
  bulkPayment?: boolean;
  bulkPaymentId?: string;
  bulkRecordingDate?: string;
  bulkRejectByPsu?: boolean;
  date: string;
  paymentProduct: string;
  paymentRecords: Array<Xs2APaymentRecord>;
  paymentService: string;
  psuIpAddress?: string;
  status?: Xs2ARequestStatus;
  tppNokRedirectUri?: string;
  tppRedirectPreferred?: boolean;
  tppRedirectUri?: string;
  xrequestId?: string;
}
