/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImmediateProcessingUiStatus } from '../models/immediate-processing-ui-status';
import { Xs2ARequest } from '../models/xs-2-a-request';
export interface Xs2ARequestWrapper {
  immediateProcessingUiStatus?: ImmediateProcessingUiStatus;
  xs2aRequest?: Xs2ARequest;
}
