/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImmediateProcessingUiStatus } from '../models/immediate-processing-ui-status';
import { Xs2APaymentRecord } from '../models/xs-2-a-payment-record';
export interface Xs2APaymentRecordWrapper {
  immediateProcessingUiStatus?: ImmediateProcessingUiStatus;
  xs2aPaymentRecord?: Xs2APaymentRecord;
}
