/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountReferenceAccounts } from '../models/account-reference-accounts';
import { AccountReferenceBalances } from '../models/account-reference-balances';
import { AccountReferenceTransactions } from '../models/account-reference-transactions';
import { AllPsd2Enum } from '../models/all-psd-2-enum';
import { AvailableAccountsEnum } from '../models/available-accounts-enum';
import { ConsentStatus } from '../models/consent-status';
export interface Xs2AConsent {
  accounts: AccountReferenceAccounts;
  allPsd2?: AllPsd2Enum;
  auditUuid: string;
  availableAccounts?: AvailableAccountsEnum;
  balances: AccountReferenceBalances;
  combinedServiceIndicator?: boolean;
  consentId: string;
  consentStatus?: ConsentStatus;
  date?: string;
  deletionDate?: string;
  frequencyPerDay?: number;
  isFullySigned?: boolean;
  lastActionDate?: string;
  psuIpAddress?: string;
  recordingDate?: string;
  recurringIndicator?: boolean;
  tppCertificateTokenHash?: string;
  tppNokRedirectUri?: string;
  tppRedirectPreferred?: boolean;
  tppRedirectUri?: string;
  transactions: AccountReferenceTransactions;
  validUntil?: string;
  xrequestId?: string;
}
