/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentRiskRatingResult } from '../models/payment-risk-rating-result';
import { TppListEntry } from '../models/tpp-list-entry';
import { Xs2APaymentRecordType } from '../models/xs-2-a-payment-record-type';
export interface Xs2APaymentRecord {
  amount?: string;
  creditorAccountCurrency?: string;
  creditorAccountIban?: string;
  creditorAddressBuildingNumber?: string;
  creditorAddressCity?: string;
  creditorAddressCountryIso?: string;
  creditorAddressPostalCode?: string;
  creditorAddressStreet?: string;
  creditorAgent?: string;
  creditorName?: string;
  currency?: string;
  debitorAccountCurrency?: string;
  debitorAccountIban?: string;
  deleted?: boolean;
  deletionDate?: string;
  endToEndIdentification?: string;
  expired?: boolean;
  immediateProcessing?: boolean;
  invalid?: boolean;
  orderCancelled?: boolean;
  orderCompleted?: boolean;
  orderDeleted?: boolean;
  orderDeletionDate?: string;
  orderFullySigned?: boolean;
  orderInitiatedByTpp?: boolean;
  orderNumber?: string;
  orderSet?: boolean;
  orderType?: Xs2APaymentRecordType;
  paymentId?: string;
  paymentProduct?: string;
  paymentRiskRatingResult?: PaymentRiskRatingResult;
  recordingDate: string;
  rejectedByPsu?: boolean;
  remittanceInformationStructured?: string;
  tppCertificateTokenHash?: string;
  tppListEntry: TppListEntry;
  tppNokRedirectUri?: string;
  tppRedirectPreferred?: boolean;
  tppRedirectUri?: string;
}
