/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TppCertificateInformationWrapper } from '../models/tpp-certificate-information-wrapper';
import { Xs2APiispConsentDataLine } from '../models/xs-2-a-piisp-consent-data-line';
export interface Xs2APiispConsentInformationHolder {
  auditUuid: string;
  certificateInformationWrapper?: TppCertificateInformationWrapper;
  consentDataLines?: Array<Xs2APiispConsentDataLine>;
}
