/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RetrieveConsentTripple } from '../models/retrieve-consent-tripple';
import { TppCertificateInformationWrapper } from '../models/tpp-certificate-information-wrapper';
export interface Xs2AConsentInformationHolder {
  auditUuid: string;
  canBeConfirmed?: boolean;
  canBeDeleted?: boolean;
  certificateInformationWrapper?: TppCertificateInformationWrapper;
  consentId?: string;
  consentTripples?: RetrieveConsentTripple;
  expiryDate?: string;
  fullySigned?: boolean;
  lastUsageDate?: string;
  recurringIndicator?: boolean;
}
